# Generated by Django 3.1.7 on 2021-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpio',
            name='name',
            field=models.CharField(default='noname_gpio', max_length=32),
        ),
    ]
