# Generated by Django 3.1.7 on 2021-03-08 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
