# Generated by Django 3.1.7 on 2021-03-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smarthome', '0002_auto_20210308_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_performed',
            field=models.BooleanField(default=False),
        ),
    ]
